# Generated by Django 2.2.5 on 2019-11-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangXe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenHangXe', models.CharField(default='', max_length=100)),
                ('AnhHangXe', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LichTrinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GioDi', models.TimeField(default='')),
                ('NgayDi', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tuyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenTuyen', models.CharField(default='', max_length=100)),
                ('DiemDi', models.CharField(default='', max_length=100)),
                ('DiemDen', models.CharField(default='', max_length=100)),
                ('ThoiGian', models.FloatField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='lichtrinh',
            name='IDTuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.Tuyen'),
        ),
    ]
