# Generated by Django 2.2.5 on 2019-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_auto_20191101_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('SoXe', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TenXe', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
