# Generated by Django 2.2.5 on 2019-11-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_xe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HangXe',
        ),
        migrations.RemoveField(
            model_name='lichtrinh',
            name='IDTuyen',
        ),
        migrations.DeleteModel(
            name='Xe',
        ),
        migrations.DeleteModel(
            name='LichTrinh',
        ),
        migrations.DeleteModel(
            name='Tuyen',
        ),
    ]
