# Generated by Django 2.2.5 on 2019-11-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ticket', '0004_auto_20191105_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangXe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenHangXe', models.CharField(default='', max_length=100)),
                ('AnhHangXe', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiXe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoaiXe', models.CharField(default='', max_length=100)),
                ('SoLuongGhe', models.SmallIntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tuyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenTuyen', models.CharField(default='', max_length=100)),
                ('DiemDi', models.CharField(default='', max_length=100)),
                ('DiemDen', models.CharField(default='', max_length=100)),
                ('ThoiGian', models.FloatField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenXe', models.CharField(default='', max_length=100)),
                ('IDHangXe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.HangXe')),
                ('IDLoaiXe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.LoaiXe')),
            ],
        ),
        migrations.CreateModel(
            name='LichTrinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GioDi', models.TimeField(default='')),
                ('NgayDi', models.DateField(default='')),
                ('IDTuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.Tuyen')),
            ],
        ),
    ]
