# Generated by Django 2.2.5 on 2019-11-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0005_hangxe_lichtrinh_loaixe_tuyen_xe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichtrinh',
            name='IDTuyen',
        ),
        migrations.RemoveField(
            model_name='xe',
            name='IDHangXe',
        ),
        migrations.RemoveField(
            model_name='xe',
            name='IDLoaiXe',
        ),
        migrations.DeleteModel(
            name='HangXe',
        ),
        migrations.DeleteModel(
            name='LichTrinh',
        ),
        migrations.DeleteModel(
            name='LoaiXe',
        ),
        migrations.DeleteModel(
            name='Tuyen',
        ),
        migrations.DeleteModel(
            name='Xe',
        ),
    ]
