# Generated by Django 2.2.5 on 2019-11-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0008_khachhang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KhachHang',
        ),
        migrations.RemoveField(
            model_name='lichtrinh',
            name='IDTuyen',
        ),
        migrations.RemoveField(
            model_name='lichtrinh',
            name='IDXe',
        ),
        migrations.RemoveField(
            model_name='xe',
            name='IDHangXe',
        ),
        migrations.RemoveField(
            model_name='xe',
            name='IDLoaiXe',
        ),
        migrations.DeleteModel(
            name='HangXe',
        ),
        migrations.DeleteModel(
            name='LichTrinh',
        ),
        migrations.DeleteModel(
            name='LoaiXe',
        ),
        migrations.DeleteModel(
            name='Tuyen',
        ),
        migrations.DeleteModel(
            name='Xe',
        ),
    ]
