# Generated by Django 2.2.5 on 2019-11-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0010_auto_20191109_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghe',
            old_name='SoLuongGhe',
            new_name='SoGhe',
        ),
        migrations.AlterField(
            model_name='giave',
            name='IDXe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.Xe'),
        ),
    ]
