# Generated by Django 2.2.5 on 2019-11-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0011_auto_20191109_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giave',
            name='IDLichTrinh',
        ),
        migrations.RemoveField(
            model_name='giave',
            name='IDXe',
        ),
        migrations.RemoveField(
            model_name='lichtrinh',
            name='IDXe',
        ),
        migrations.RemoveField(
            model_name='trangthaidatvexe',
            name='IDLichTrinh',
        ),
        migrations.RemoveField(
            model_name='vexe',
            name='IDGhe',
        ),
        migrations.RemoveField(
            model_name='vexe',
            name='IDGiaVe',
        ),
        migrations.RemoveField(
            model_name='vexe',
            name='IDKhachHang',
        ),
        migrations.RemoveField(
            model_name='vexe',
            name='IDLichTrinh',
        ),
        migrations.RemoveField(
            model_name='xe',
            name='IDHangXe',
        ),
        migrations.RemoveField(
            model_name='xe',
            name='IDLoaiXe',
        ),
        migrations.DeleteModel(
            name='Ghe',
        ),
        migrations.DeleteModel(
            name='GiaVe',
        ),
        migrations.DeleteModel(
            name='HangXe',
        ),
        migrations.DeleteModel(
            name='KhachHang',
        ),
        migrations.DeleteModel(
            name='LichTrinh',
        ),
        migrations.DeleteModel(
            name='LoaiXe',
        ),
        migrations.DeleteModel(
            name='TrangThaiDatVeXe',
        ),
        migrations.DeleteModel(
            name='VeXe',
        ),
        migrations.DeleteModel(
            name='Xe',
        ),
    ]
