# Generated by Django 2.2.5 on 2019-11-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ticket', '0012_auto_20191110_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ghe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoGhe', models.SmallIntegerField(default='')),
                ('TinhTrang', models.BooleanField(default=True)),
                ('MoTa', models.TextField(default='', max_length=100, null=True)),
                ('NgayThem', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiaVe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GiaVeXe', models.IntegerField(default='')),
                ('TinhTrang', models.BooleanField(default=True)),
                ('MoTa', models.TextField(default='', max_length=100, null=True)),
                ('NgayThem', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HangXe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenHangXe', models.CharField(default='', max_length=100)),
                ('AnhHangXe', models.ImageField(default='', upload_to='')),
                ('DienThoai', models.CharField(default='', max_length=10)),
                ('TinhTrang', models.BooleanField(default=True)),
                ('MoTa', models.TextField(default='', max_length=100, null=True)),
                ('NgayThem', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenKhachHang', models.CharField(default='', max_length=100)),
                ('DienThoai', models.CharField(default='', max_length=10)),
                ('Email', models.CharField(default='', max_length=100)),
                ('DiemDon', models.CharField(default='', max_length=100)),
                ('GhiChu', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LichTrinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLichTrinh', models.CharField(default='', max_length=100)),
                ('DiemDi', models.CharField(default='', max_length=100)),
                ('DiemDen', models.CharField(default='', max_length=100)),
                ('ThoiGian', models.FloatField(default='')),
                ('GioDi', models.TimeField(default='')),
                ('NgayDi', models.DateField(default='')),
                ('TinhTrang', models.BooleanField(default=True)),
                ('MoTa', models.TextField(default='', max_length=100, null=True)),
                ('NgayThem', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiXe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoaiXe', models.CharField(default='', max_length=100)),
                ('SoLuongGhe', models.SmallIntegerField(default='')),
                ('TinhTrang', models.BooleanField(default=True)),
                ('MoTa', models.TextField(default='', max_length=100, null=True)),
                ('NgayThem', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenXe', models.CharField(default='', max_length=100)),
                ('TinhTrang', models.BooleanField(default=True)),
                ('MoTa', models.TextField(default='', max_length=100, null=True)),
                ('NgayThem', models.DateField(auto_now=True)),
                ('IDHangXe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.HangXe')),
                ('IDLichTrinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.LichTrinh')),
                ('IDLoaiXe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.LoaiXe')),
            ],
        ),
        migrations.CreateModel(
            name='VeXe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TinhTrang', models.BooleanField(default=True)),
                ('MoTa', models.TextField(default='', max_length=100, null=True)),
                ('NgayThem', models.DateField(auto_now=True)),
                ('IDGhe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.Ghe')),
                ('IDGiaVe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.GiaVe')),
                ('IDKhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.KhachHang')),
                ('IDLichTrinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.LichTrinh')),
            ],
        ),
        migrations.CreateModel(
            name='TrangThaiDatVeXe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoGhe', models.SmallIntegerField(default='')),
                ('TrangThai', models.BooleanField(default=False)),
                ('IDLichTrinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.LichTrinh')),
            ],
        ),
        migrations.AddField(
            model_name='giave',
            name='IDLichTrinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.LichTrinh'),
        ),
        migrations.AddField(
            model_name='giave',
            name='IDXe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.Xe'),
        ),
        migrations.AddField(
            model_name='ghe',
            name='IDXe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticket.Xe'),
        ),
    ]
